### ISSUE TITLE
Error when accessing login page

### ISSUE THREAD

**Issue by dalareo** [pi0/gluu-docker#1]
I redirect 80 port at proxy container to 80 port in my host and go to:

https://0.0.0.0/identity/login?cid=1

I get error: Unable to connect

**Comment by pi0** [comment]
@dalareo Congratulations for being first tester :) Being redirected to `https`  is a little odd & redirection should not happen as `http_gluu.conf` is configured to serve http only. also 0.0.0.0 is an special ip indicating any host. Would you please directly try one of [http://localhost](http://localhost) or  [http://127.0.0.1](http://127.0.0.1) urls?

**Comment by dalareo** [comment]
I am also redirected to https with localhost and 127.0.0.1 ;((

**Comment by pi0** [comment]
@dalareo Isn't that from your browser cache ? maybe try with another browser or using `curl -I http://localhost`. If problem exists that may be with gluu that redirects to https. (actually i was using and testing bundle with nginx-proxy which automatically adds ssl)

**Comment by dalareo** [comment]
culs -I localhost gives:

````
HTTP/1.1 302 Found
Date: Fri, 13 Jan 2017 12:02:21 GMT
Server: Apache/2.4.18 (Ubuntu)
X-Frame-Options: SAMEORIGIN
Location: http://localhost/identity/
Content-Type: text/html; charset=iso-8859-1
````

**Comment by pi0** [comment]
so curl again http://localhost/identity/ :)) (tip: or use -L flag so that curl follows redirections)

**Comment by dalareo** [comment]
When using -L flag I get:

HTTP/1.1 302 Found
Date: Fri, 13 Jan 2017 12:13:13 GMT
Server: Jetty(9.3.15.v20161220)
X-Frame-Options: SAMEORIGIN
Location: https://localhost/identity/

curl: (7) Failed to connect to localhost port 443: Connection refused

I then redirect 443 port at host to 443 port at container (though I think it is not exposed) and I get:

HTTP/1.1 302 Found
Date: Fri, 13 Jan 2017 12:14:36 GMT
Server: Jetty(9.3.15.v20161220)
X-Frame-Options: SAMEORIGIN
Location: https://localhost/identity/

curl: (35) gnutls_handshake() failed: An unexpected TLS packet was received.

**Comment by dalareo** [comment]
My docker-compose.yml file is:

version: '2'
services:
    
    #--------------------------------
    # Gluu ldap server
    #--------------------------------
    ldap:
        image: quay.io/gluu/gluu
        command: ldap
        volumes:
            - ./data/gluu_data:/opt/gluu/data
            - ./data/gluu_schema:/opt/gluu/schema
            - ./data/gluu_etc:/etc/gluu
            - ./data/gluu_certs:/etc/certs
            - ./data/gluu_install:/install/output
            - ./data/gluu_ox:/var/ox
        env_file: env
        network_mode: bridge
        expose: [1636]
        restart: always

    #--------------------------------
    # Gluu identity(oxtrust) service
    #--------------------------------
    identity:
        image: quay.io/gluu/gluu
        command: identity
        hostname: identity
        volumes_from: [ldap]
        network_mode: bridge
        links: [ldap] 
        expose: [80]
        restart: always

    #--------------------------------
    # Gluu oxauth service
    #--------------------------------
    oxauth:
        image: quay.io/gluu/gluu
        command: oxauth
        hostname: oxauth
        volumes_from: [ldap]
        network_mode: bridge
        links: [ldap] 
        expose: [80]
        restart: always
        
    #--------------------------------
    # Gluu proxy
    #--------------------------------
    proxy:
        image: quay.io/gluu/gluu
        command: proxy
        volumes_from: [ldap]
        links: [identity,oxauth]
        expose: [80]
        network_mode: bridge
        restart: always
        ports:
           - 80:80
           - 443:443

**Comment by pi0** [comment]
That's true. it seems Gluu internally strictly checks for https headers. I'll make a workaround soon :)

**Comment by pi0** [comment]
@dalareo please pull repo and rebuild your containers. problem should be resolved with early https header injection.

**Comment by dalareo** [comment]
Still get error when accessign with web browser: An error occurred during a connection to localhost. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECORD_TOO_LONG

If I execute curl -L http://localhost/identity I get:

curl: (35) gnutls_handshake() failed: An unexpected TLS packet was received.

**Comment by lgleim** [comment]
You should probably change the http_gluu.conf to redirect to https, not http for all the hosts to fix this. The redirect comes from the identity server and the proxy cannot handle the https request because no certificate is configured. Otherwise this might even lead to a redirection loop.

**Comment by pi0** [comment]
@lgleim The main reason about this special type of config was that glue uses self-signed certificates by default and this image was supposed to use like this:
`upsteam with valid certs (443) => Apache Docker (80)  => Identity Server with invalid cert (443)`

So we **need a SSL upstream proxy** to this works. In next release apache will listen both 80 & 443 so we may use this image without an upstream...

**Comment by lgleim** [comment]
Thanks for this crucial pointer. I will create a pull request for the readme as this does not appear self documenting to me...

**Comment by pi0** [comment]
#5 by @lgleim should fix this now. feel free to repoen this issue.
